# Generated by Django 4.2.7 on 2026-06-16 00:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import medical.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(choices=[('xray', 'X-Ray'), ('mri', 'MRI'), ('ct', 'CT-Scan')], max_length=10)),
                ('body_part', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=medical.models.get_upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('diagnosis', models.TextField(blank=True)),
                ('recommendations', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='patientprofile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='prescription',
        ),
        migrations.AlterField(
            model_name='consultation',
            name='scheduled_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(default='scheduled', max_length=20),
        ),
        migrations.DeleteModel(
            name='MedicalScan',
        ),
        migrations.DeleteModel(
            name='PatientProfile',
        ),
    ]
