# Generated by Django 5.2.15 on 2026-06-16 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_patientscan_remove_patientprofile_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conditions', models.TextField(blank=True, help_text='Pre-existing conditions')),
                ('allergies', models.TextField(blank=True, help_text='Allergies')),
                ('medications', models.TextField(blank=True, help_text='Current medications')),
                ('surgeries', models.TextField(blank=True, help_text='Previous surgeries')),
                ('family_history', models.TextField(blank=True, help_text='Family medical history')),
                ('lifestyle', models.TextField(blank=True, help_text='Lifestyle information')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medical_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
