# Generated by Django 4.2.7 on 2026-06-18 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medical', '0005_consultationpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='prescription',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientscan',
            name='doctor_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientscan',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientscan',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_scans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='scheduled_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientscan',
            name='body_part',
            field=models.CharField(choices=[('spine', 'Spine'), ('knee', 'Knee'), ('hip', 'Hip'), ('shoulder', 'Shoulder'), ('elbow', 'Elbow'), ('wrist', 'Wrist'), ('ankle', 'Ankle'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='patientscan',
            name='scan_type',
            field=models.CharField(choices=[('xray', 'X-Ray'), ('mri', 'MRI'), ('ct', 'CT-Scan'), ('ultrasound', 'Ultrasound')], max_length=20),
        ),
        migrations.AlterField(
            model_name='patientscan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('reviewed', 'Reviewed'), ('needs_followup', 'Needs Follow-up')], default='pending', max_length=20),
        ),
    ]
